[package]
name = "logic_circuit_simulator"
version = "0.1.0"
authors = ["remtori <lqvu99@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitvec = "0.20"
wasm-bindgen = "0.2.49"
