[package]
name = "logic_circuit_simulator"
version = "0.1.0"
authors = ["remtori <lqvu99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
