env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:@typescript-eslint/recommended'
  - 'preact'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
settings:
  react:
    version: 'detect'
rules:
  linebreak-style:
    - error
    - unix
  'prettier/prettier':
    - error
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars': 'error'
  no-unused-vars: off
  max-len:
    - warn
    - 120
